# Generated by Django 2.2.4 on 2021-05-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20210527_0101'),
        ('usuarios', '0006_auto_20210527_0101'),
        ('inscripciones', '0003_auto_20210524_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('participante', 'taller')},
        ),
    ]
