# Generated by Django 2.2.4 on 2021-05-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_auto_20210522_1711'),
        ('cursos', '0002_curso_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=250)),
                ('confirmado', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='usuarios.Usuario')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='cursos.Curso')),
            ],
        ),
    ]
